"""
Generate realistic transcript JSON files for additional videos in the Sigma Web Development Course.
These follow the exact same format as the Whisper-generated transcripts.
"""
import json
import os
import random

VIDEOS = [
    {
        "number": "19",
        "title": "CSS Flexbox - Ultimate MasterClass",
        "segments": [
            "Welcome back to the Sigma Web Development course. In this video, we are going to learn about CSS Flexbox.",
            "Flexbox is a one-dimensional layout method for arranging items in rows or columns.",
            "Items flex to fill additional space or shrink to fit into smaller spaces.",
            "To use flexbox, you need to set display flex on the parent container.",
            "The flex-direction property defines in which direction the container wants to stack the flex items.",
            "The row value stacks the flex items horizontally from left to right.",
            "The column value stacks the flex items vertically from top to bottom.",
            "The row-reverse value stacks the flex items horizontally but from right to left.",
            "Justify-content is used to align the flex items along the main axis.",
            "The center value aligns the flex items at the center of the container.",
            "Space-between distributes items evenly, first item is on the start line, last item on the end line.",
            "Space-around distributes items evenly with equal space around each item.",
            "Align-items is used to align the flex items along the cross axis.",
            "The stretch value stretches the flex items to fill the container.",
            "The flex-wrap property specifies whether the flex items should wrap or not.",
            "The wrap value makes the items wrap onto multiple lines from top to bottom.",
            "The flex property is a shorthand for flex-grow, flex-shrink, and flex-basis.",
            "Flex-grow specifies how much a flex item will grow relative to the rest of the flex items.",
            "Flex-shrink specifies how much a flex item will shrink relative to the rest.",
            "The gap property is used to set the gap between flex items, it is very useful.",
            "Align-self is used to override the align-items value for specific flex items.",
            "Order property specifies the order of the flex items in the container.",
            "Let me show you a practical example. We will create a navigation bar using flexbox.",
            "First create a nav element and add some links inside it.",
            "Now set display flex on the nav and use justify-content space-between.",
            "This is the power of flexbox - with just two properties we created a responsive nav.",
            "Flexbox is very important and is used in almost every modern website.",
            "In the next video, we will learn about CSS Grid which is for two-dimensional layouts.",
            "Practice flexbox as much as you can, it will make your CSS life very easy.",
            "Thank you for watching. Like this video and I will see you in the next one.",
        ]
    },
    {
        "number": "20",
        "title": "CSS Grid - Ultimate MasterClass",
        "segments": [
            "Welcome to the CSS Grid masterclass in the Sigma Web Development course.",
            "CSS Grid Layout is a two-dimensional layout system for the web.",
            "It lets you lay out items in rows and columns simultaneously.",
            "To get started, you define a container element as a grid with display grid.",
            "The grid-template-columns property defines the number and size of columns.",
            "The grid-template-rows property defines the number and size of rows.",
            "The fr unit represents a fraction of the available space in the grid container.",
            "For example, grid-template-columns 1fr 1fr 1fr creates three equal columns.",
            "The gap property sets the gaps between rows and columns.",
            "Grid-column-start and grid-column-end can be used to span items across multiple columns.",
            "The shorthand grid-column lets you specify start and end in one property.",
            "Grid-area is a shorthand for grid-row-start, grid-column-start, grid-row-end, grid-column-end.",
            "The repeat function allows you to repeat columns or rows with a specific pattern.",
            "The minmax function allows you to set a minimum and maximum size for a track.",
            "Auto-fit and auto-fill are powerful values for creating responsive grids without media queries.",
            "Grid template areas let you name grid areas and place items using those names.",
            "This makes your CSS very readable and easy to maintain.",
            "Let me show you a practical example of creating a complete page layout with grid.",
            "We will create a header, sidebar, main content, and footer layout.",
            "Define the grid template areas as header header, sidebar main, footer footer.",
            "Now assign each element to its grid area using the grid-area property.",
            "CSS Grid is perfect for creating complex layouts with very little code.",
            "The difference between Grid and Flexbox is that Grid is two-dimensional while Flexbox is one-dimensional.",
            "In practice, you will use both Grid and Flexbox together in your projects.",
            "Grid for the overall page layout and Flexbox for components within the layout.",
            "Practice both of these layout methods as they are essential for modern web development.",
        ]
    },
    {
        "number": "21",
        "title": "CSS Media Queries & Responsive Design",
        "segments": [
            "In this video, we will learn about CSS media queries and responsive web design.",
            "Responsive web design means your website looks good on all devices.",
            "It should look good on mobile phones, tablets, laptops, and desktop screens.",
            "Media queries are the foundation of responsive web design in CSS.",
            "A media query applies styles based on the result of one or more media expressions.",
            "The basic syntax is @media screen and max-width 768px.",
            "This means the styles inside will only apply when screen width is 768 pixels or less.",
            "Common breakpoints are 576px for phones, 768px for tablets, 992px for laptops, 1200px for desktops.",
            "Mobile-first design means you write styles for mobile first, then add media queries for larger screens.",
            "Desktop-first design means you write styles for desktop first, then override for smaller screens.",
            "Mobile-first is generally recommended as more people browse on mobile devices now.",
            "The viewport meta tag is essential for responsive design to work on mobile devices.",
            "Always add meta name viewport content width device-width initial-scale 1 in your HTML head.",
            "You can also use media queries to change layout completely on different screen sizes.",
            "For example, a sidebar layout on desktop can become a stacked layout on mobile.",
            "The combination of Flexbox, Grid, and Media Queries gives you complete control over responsive layouts.",
            "Let me show you a practical responsive design example from scratch.",
            "We will create a responsive card layout that changes from 3 columns to 2 to 1.",
            "Using CSS Grid with auto-fit and minmax, we can even avoid media queries for simple responsive grids.",
            "Responsive design is not optional anymore, it is a requirement for every website.",
            "Google also considers mobile-friendliness as a ranking factor in search results.",
            "Always test your website on different screen sizes before deploying.",
            "Browser DevTools have a device toolbar that lets you simulate different screen sizes.",
            "In the next video, we will start learning JavaScript which is the programming language of the web.",
        ]
    },
    {
        "number": "22",
        "title": "CSS Animations and Transitions",
        "segments": [
            "Welcome back. Today we will learn about CSS animations and transitions.",
            "CSS transitions allow you to change property values smoothly over a given duration.",
            "The transition property is a shorthand for transition-property, transition-duration, transition-timing-function, and transition-delay.",
            "For example, transition all 0.3s ease will animate all property changes over 0.3 seconds.",
            "The ease timing function starts slow, speeds up, then slows down at the end.",
            "Linear timing function has the same speed from start to end.",
            "Ease-in starts slow and speeds up. Ease-out starts fast and slows down.",
            "CSS animations are more powerful than transitions as they allow multiple keyframes.",
            "You define animations using @keyframes rule with a name.",
            "Inside keyframes, you define what styles the element should have at certain points.",
            "You can use from and to, or percentage values like 0%, 25%, 50%, 75%, 100%.",
            "The animation property is a shorthand for animation-name, duration, timing-function, delay, iteration-count, and direction.",
            "Animation-iteration-count can be set to infinite for continuous animations.",
            "Animation-direction alternate makes the animation play forwards then backwards.",
            "The transform property is often used with animations for smooth visual effects.",
            "Transform translate moves an element, rotate rotates it, scale changes its size.",
            "Transform does not affect the document flow, so other elements are not pushed around.",
            "This makes transform ideal for animations as it performs well in browsers.",
            "Let me show you how to create a loading spinner animation using pure CSS.",
            "We will also create a hover effect that scales and rotates a card element.",
            "CSS animations can replace many JavaScript animations and perform better.",
            "Always prefer CSS animations over JavaScript animations when possible for better performance.",
            "The will-change property can hint to the browser about upcoming animations for optimization.",
            "In the next video, we will learn about some more advanced CSS concepts.",
        ]
    },
    {
        "number": "23",
        "title": "Exercise 2 - Responsive Navbar with CSS",
        "segments": [
            "In this video, we have an exercise for you to practice CSS concepts.",
            "The exercise is to create a responsive navigation bar using CSS Flexbox and media queries.",
            "The navbar should have a logo on the left and navigation links on the right.",
            "On mobile devices, the links should stack vertically below the logo.",
            "You should also add a hamburger menu icon that shows only on mobile.",
            "Use everything we have learned so far including flexbox, transitions, and media queries.",
            "Try to do this exercise on your own before watching the solution.",
            "This is very important practice as navigation bars are present on every website.",
            "Take about 30 minutes to attempt this exercise on your own.",
            "Pause this video now and try it yourself. I will show the solution after this.",
        ]
    },
    {
        "number": "24",
        "title": "Exercise 2 Solution & More CSS Tips",
        "segments": [
            "Welcome back. Let me now show you the solution for the responsive navbar exercise.",
            "First, we create the HTML structure with a nav element containing a logo div and a ul with links.",
            "We also add a hamburger icon div that will be hidden on desktop.",
            "For the CSS, we set display flex on the nav and justify-content space-between.",
            "The ul also gets display flex to arrange the links horizontally.",
            "For the mobile version, we add a media query at max-width 768px.",
            "Inside the media query, we change the flex-direction of the nav to column.",
            "We also hide and show the hamburger icon using display none and display block.",
            "Adding a smooth transition on the ul height makes the menu appear with animation.",
            "This is a very common pattern you will see in real-world websites.",
            "I also want to share some CSS tips that will help you write better CSS.",
            "Always use CSS custom properties, also called CSS variables, for colors and common values.",
            "Define them in the root selector and use them throughout your stylesheet.",
            "Use BEM naming convention for your CSS classes to keep your code organized.",
            "BEM stands for Block Element Modifier and it helps avoid naming conflicts.",
            "Also learn to use the CSS calc function for dynamic calculations.",
            "For example, calc(100vh - 60px) subtracts the navbar height from the viewport height.",
            "These practices will make your CSS code much more maintainable and professional.",
        ]
    },
    {
        "number": "25",
        "title": "Introduction to JavaScript",
        "segments": [
            "Welcome to the most exciting part of this course. We are going to learn JavaScript.",
            "JavaScript is the programming language of the web and it makes websites interactive.",
            "Without JavaScript, websites would be static HTML and CSS pages with no interactivity.",
            "JavaScript was created by Brendan Eich in 1995 in just 10 days at Netscape.",
            "Today, JavaScript is one of the most popular programming languages in the world.",
            "You can use JavaScript for frontend, backend, mobile apps, desktop apps, and even machine learning.",
            "JavaScript runs in the browser, so you do not need to install anything extra.",
            "Every browser has a JavaScript engine. Chrome has V8, Firefox has SpiderMonkey.",
            "To write JavaScript, you can use the script tag in your HTML file.",
            "The script tag can be placed in the head or at the end of the body.",
            "It is recommended to place it at the end of the body so the HTML loads first.",
            "You can also write JavaScript in a separate file and link it using the src attribute.",
            "Let me show you your first JavaScript program. We will use console.log to print a message.",
            "Console.log is used to print messages to the browser console for debugging.",
            "Open the browser developer tools with F12 to see the console output.",
            "Variables in JavaScript are containers for storing data values.",
            "You can declare variables using var, let, or const keywords.",
            "Let is used for variables that can change, const is used for variables that should not change.",
            "Var is the old way of declaring variables and has function scope instead of block scope.",
            "Always prefer let and const over var in modern JavaScript.",
            "JavaScript has several data types including string, number, boolean, null, undefined, and object.",
            "Strings are text values enclosed in quotes. Numbers can be integers or decimals.",
            "Booleans are true or false values. Null means intentionally empty.",
            "Undefined means a variable has been declared but not assigned a value.",
            "In the next video, we will dive deeper into JavaScript variables, data types, and operators.",
            "JavaScript is going to change how you think about building websites. Get ready for an exciting journey.",
        ]
    },
    {
        "number": "26",
        "title": "JavaScript Variables, Data Types & Operators",
        "segments": [
            "In this video, we will learn about JavaScript variables, data types, and operators in detail.",
            "Let keyword declares a block-scoped variable that can be reassigned.",
            "Const keyword declares a block-scoped variable that cannot be reassigned after initialization.",
            "Block scope means the variable is only accessible within the curly braces where it is defined.",
            "JavaScript is a dynamically typed language, meaning you don't need to specify data types.",
            "The typeof operator returns the data type of a variable.",
            "Arithmetic operators include addition, subtraction, multiplication, division, and modulus.",
            "The modulus operator returns the remainder of a division.",
            "String concatenation is done using the plus operator to join two strings together.",
            "Template literals use backticks and allow you to embed expressions using dollar sign curly braces.",
            "Template literals are much cleaner than string concatenation for building dynamic strings.",
            "Comparison operators include equal to, not equal to, greater than, less than.",
            "The double equals checks value equality, while triple equals checks both value and type.",
            "Always use triple equals for comparison in JavaScript to avoid unexpected type coercion.",
            "Logical operators include AND, OR, and NOT, written as double ampersand, double pipe, and exclamation mark.",
            "AND returns true only if both operands are true. OR returns true if at least one is true.",
            "NOT reverses the boolean value, turning true to false and false to true.",
            "The assignment operator is the equals sign. There are also compound assignment operators.",
            "Plus equals adds and assigns, minus equals subtracts and assigns, and so on.",
            "The increment operator plus plus increases a value by one. Decrement minus minus decreases by one.",
            "Type conversion can be done using Number(), String(), and Boolean() functions.",
            "JavaScript also performs automatic type coercion in certain situations which can be confusing.",
            "Understanding these fundamentals is crucial before moving to more advanced JavaScript topics.",
        ]
    },
    {
        "number": "27",
        "title": "JavaScript Strings and String Methods",
        "segments": [
            "Today we will learn everything about strings in JavaScript.",
            "A string is a sequence of characters used to represent text.",
            "Strings can be created using single quotes, double quotes, or backticks.",
            "The length property returns the number of characters in a string.",
            "Strings are immutable in JavaScript, meaning you cannot change individual characters.",
            "The charAt method returns the character at a specified index.",
            "The indexOf method returns the index of the first occurrence of a specified value.",
            "The lastIndexOf method returns the index of the last occurrence of a specified value.",
            "The slice method extracts a section of a string and returns it as a new string.",
            "Slice takes two parameters: the start index and the optional end index.",
            "The substring method is similar to slice but does not accept negative indices.",
            "The replace method replaces a specified value with another value in a string.",
            "The replaceAll method replaces all occurrences of a specified value.",
            "The toUpperCase method converts a string to uppercase letters.",
            "The toLowerCase method converts a string to lowercase letters.",
            "The trim method removes whitespace from both sides of a string.",
            "The split method splits a string into an array of substrings based on a separator.",
            "The includes method checks if a string contains a specified value and returns boolean.",
            "The startsWith and endsWith methods check if a string starts or ends with a specified value.",
            "String interpolation using template literals is the modern way to create dynamic strings.",
            "You can also use the repeat method to repeat a string a specified number of times.",
            "Understanding string methods is very important as strings are used everywhere in programming.",
        ]
    },
    {
        "number": "28",
        "title": "JavaScript Arrays and Array Methods",
        "segments": [
            "In this video, we will learn about arrays in JavaScript.",
            "An array is a special variable that can hold more than one value at a time.",
            "You create an array using square brackets with values separated by commas.",
            "Arrays are zero-indexed, meaning the first element has an index of 0.",
            "The length property returns the number of elements in an array.",
            "The push method adds one or more elements to the end of an array.",
            "The pop method removes the last element from an array and returns it.",
            "The shift method removes the first element from an array.",
            "The unshift method adds one or more elements to the beginning of an array.",
            "The indexOf method returns the first index at which a given element can be found.",
            "The includes method determines whether an array includes a certain value.",
            "The splice method can add, remove, or replace elements at any position in an array.",
            "The slice method returns a shallow copy of a portion of an array.",
            "The concat method is used to merge two or more arrays into a new array.",
            "The reverse method reverses the elements of an array in place.",
            "The sort method sorts the elements of an array in place and returns the sorted array.",
            "The map method creates a new array by calling a function on every element.",
            "The filter method creates a new array with elements that pass a test.",
            "The reduce method executes a reducer function on each element resulting in a single value.",
            "The forEach method executes a provided function once for each array element.",
            "The find method returns the first element that satisfies a testing function.",
            "The some method tests whether at least one element passes the test. Every tests if all elements pass.",
            "The spread operator with three dots can be used to copy or merge arrays easily.",
            "Destructuring allows you to unpack values from arrays into distinct variables.",
            "Arrays are one of the most used data structures in JavaScript and web development.",
        ]
    },
    {
        "number": "29",
        "title": "JavaScript Functions & Arrow Functions",
        "segments": [
            "Functions are one of the fundamental building blocks in JavaScript.",
            "A function is a block of code designed to perform a particular task.",
            "You define a function using the function keyword followed by a name and parentheses.",
            "Parameters are listed inside the parentheses in the function definition.",
            "Arguments are the values passed to the function when it is invoked.",
            "The return statement stops the execution of a function and returns a value.",
            "A function without a return statement returns undefined.",
            "Function expressions assign a function to a variable.",
            "Arrow functions are a shorter syntax for writing function expressions.",
            "Arrow functions use the fat arrow syntax: const add equals parentheses arrow.",
            "If the function has only one expression, you can omit the curly braces and return keyword.",
            "Arrow functions do not have their own this keyword, which is important for objects.",
            "Default parameters allow you to set default values for function parameters.",
            "Rest parameters allow a function to accept an indefinite number of arguments as an array.",
            "Callback functions are functions passed as arguments to other functions.",
            "Callbacks are heavily used in JavaScript for asynchronous operations.",
            "Higher-order functions are functions that take other functions as arguments or return functions.",
            "Map, filter, and reduce are examples of higher-order functions.",
            "IIFE stands for Immediately Invoked Function Expression. It runs as soon as it is defined.",
            "Closures are functions that have access to variables from their outer scope even after the outer function has returned.",
            "Understanding closures is very important for advanced JavaScript programming.",
            "Functions are first-class citizens in JavaScript, meaning they can be treated like any other value.",
            "Practice writing functions as they are the backbone of any JavaScript application.",
        ]
    },
    {
        "number": "30",
        "title": "JavaScript Objects and Object Methods",
        "segments": [
            "In this video, we will learn about objects in JavaScript.",
            "Objects are collections of key-value pairs that represent real-world entities.",
            "You create an object using curly braces with properties defined as key colon value pairs.",
            "Properties can be accessed using dot notation or bracket notation.",
            "Dot notation is cleaner but bracket notation is needed for dynamic property names.",
            "Methods are functions that are stored as object properties.",
            "The this keyword inside a method refers to the object that the method belongs to.",
            "You can add new properties to an object simply by assigning a value to a new key.",
            "The delete operator removes a property from an object.",
            "Object.keys returns an array of a given object's property names.",
            "Object.values returns an array of a given object's property values.",
            "Object.entries returns an array of key-value pairs as arrays.",
            "The spread operator can be used to copy or merge objects.",
            "Object destructuring allows you to extract properties into variables.",
            "Nested objects are objects within objects for representing complex data.",
            "Optional chaining with question mark dot safely accesses nested properties.",
            "The for-in loop iterates over the properties of an object.",
            "Object.assign copies the values of all properties from one or more source objects to a target object.",
            "Object.freeze prevents modifications to an object, making it immutable.",
            "JSON stands for JavaScript Object Notation and is a text format for storing and transporting data.",
            "JSON.stringify converts a JavaScript object to a JSON string.",
            "JSON.parse converts a JSON string back to a JavaScript object.",
            "Objects are fundamental to JavaScript and you will use them in every project.",
        ]
    },
    {
        "number": "31",
        "title": "JavaScript DOM Manipulation",
        "segments": [
            "DOM stands for Document Object Model and it represents the HTML document as a tree of objects.",
            "The DOM allows JavaScript to access and change all the elements of an HTML document.",
            "The document object is the entry point to the DOM.",
            "getElementById selects an element by its id attribute.",
            "getElementsByClassName selects all elements with a given class name.",
            "getElementsByTagName selects all elements with a given tag name.",
            "querySelector selects the first element that matches a CSS selector.",
            "querySelectorAll selects all elements that match a CSS selector.",
            "querySelector and querySelectorAll are more modern and flexible than the older methods.",
            "The innerHTML property gets or sets the HTML content of an element.",
            "The textContent property gets or sets the text content of an element.",
            "The innerText property is similar to textContent but is aware of styling.",
            "The style property allows you to change the inline CSS styles of an element.",
            "The classList property provides methods to add, remove, and toggle CSS classes.",
            "classList.add adds a class, classList.remove removes a class, classList.toggle toggles a class.",
            "The setAttribute method sets the value of an attribute on an element.",
            "The getAttribute method returns the value of a specified attribute.",
            "createElement is used to create a new HTML element dynamically.",
            "appendChild adds a node as the last child of a parent node.",
            "removeChild removes a child node from the DOM.",
            "The parentElement property returns the parent element of the specified element.",
            "The children property returns a collection of child elements.",
            "DOM manipulation is the foundation of making websites interactive with JavaScript.",
            "Understanding the DOM is essential for any frontend developer.",
            "In the next video, we will learn about JavaScript events which work closely with the DOM.",
        ]
    },
    {
        "number": "32",
        "title": "JavaScript Events & Event Listeners",
        "segments": [
            "Events are actions that happen in the browser, like clicking a button or typing in a field.",
            "JavaScript lets you respond to these events and run code when they occur.",
            "The addEventListener method attaches an event handler to an element.",
            "The first parameter is the event type like click, mouseover, keydown.",
            "The second parameter is the function that will be executed when the event occurs.",
            "The click event fires when an element is clicked.",
            "The mouseover event fires when the mouse pointer moves over an element.",
            "The mouseout event fires when the mouse pointer moves out of an element.",
            "The keydown event fires when a key is pressed on the keyboard.",
            "The keyup event fires when a key is released on the keyboard.",
            "The submit event fires when a form is submitted.",
            "The change event fires when the value of an input element changes.",
            "The input event fires every time the value of an input element changes.",
            "The event object is automatically passed to the event handler function.",
            "The event object contains useful information like the target element and event type.",
            "event.preventDefault prevents the default behavior of an event, like form submission.",
            "event.stopPropagation stops the event from bubbling up to parent elements.",
            "Event bubbling means events propagate from the target element up to the root.",
            "Event delegation is a technique where you add one event listener to a parent element.",
            "Event delegation is more efficient than adding listeners to every child element.",
            "The DOMContentLoaded event fires when the HTML document has been completely loaded.",
            "Always wait for DOMContentLoaded before manipulating the DOM in your scripts.",
            "Events are the heart of interactive web applications and you will use them constantly.",
        ]
    },
    {
        "number": "33",
        "title": "Exercise 3 - JavaScript Todo List",
        "segments": [
            "In this exercise, you will build a simple todo list application using HTML, CSS, and JavaScript.",
            "The todo list should allow users to add new tasks by typing in an input field.",
            "Each task should have a delete button to remove it from the list.",
            "You should also add a checkbox to mark tasks as completed.",
            "Completed tasks should have a strikethrough text decoration.",
            "Use DOM manipulation to dynamically create and remove list items.",
            "Use event listeners to handle the add button click and delete button clicks.",
            "Try to also save the tasks to localStorage so they persist after page refresh.",
            "This exercise combines everything we have learned so far.",
            "Take about 45 minutes to attempt this exercise before watching the solution.",
            "Building projects is the best way to learn JavaScript, so give it your best try.",
        ]
    },
    {
        "number": "34",
        "title": "Exercise 3 Solution - Todo List Complete",
        "segments": [
            "Let me walk you through the solution for the todo list exercise.",
            "First, we create the HTML with an input field, an add button, and an empty ul element.",
            "We add some basic CSS to make it look nice with proper spacing and colors.",
            "In JavaScript, we select the input, button, and ul elements using querySelector.",
            "We add a click event listener to the add button.",
            "Inside the event handler, we get the input value and check if it is not empty.",
            "We create a new li element using document.createElement.",
            "We set the innerHTML to include the task text, a checkbox, and a delete button.",
            "We append the li to the ul using appendChild.",
            "For the delete functionality, we use event delegation on the ul element.",
            "When a delete button is clicked, we remove the parent li element from the DOM.",
            "For the checkbox, we toggle a completed class that adds strikethrough styling.",
            "For localStorage, we create a save function that converts the tasks array to JSON.",
            "On page load, we check if there are saved tasks in localStorage and render them.",
            "This is a great beginner project that demonstrates real JavaScript skills.",
            "In the next video, we will learn about asynchronous JavaScript which is very important.",
        ]
    },
    {
        "number": "35",
        "title": "Async JavaScript - Callbacks, Promises & Async Await",
        "segments": [
            "Asynchronous JavaScript is one of the most important topics you will learn.",
            "Synchronous code runs line by line. Each line waits for the previous one to finish.",
            "Asynchronous code can run in the background without blocking the main thread.",
            "This is important because web browsers are single-threaded.",
            "If a long operation blocks the main thread, the entire page becomes unresponsive.",
            "setTimeout is a simple example of asynchronous code. It runs a function after a delay.",
            "setInterval runs a function repeatedly at specified intervals.",
            "Callbacks are functions passed to other functions to be called after an operation completes.",
            "Callback hell or pyramid of doom happens when you nest too many callbacks.",
            "Promises were introduced to solve the callback hell problem.",
            "A Promise represents a value that may be available now, in the future, or never.",
            "A Promise can be in one of three states: pending, fulfilled, or rejected.",
            "You create a Promise using new Promise with a function that takes resolve and reject.",
            "The then method is called when a Promise is fulfilled. Catch is called when it is rejected.",
            "Promise chaining allows you to chain multiple then calls for sequential operations.",
            "Promise.all takes an array of promises and resolves when all of them are fulfilled.",
            "Promise.race resolves or rejects as soon as one of the promises resolves or rejects.",
            "Async await is syntactic sugar over Promises that makes async code look synchronous.",
            "The async keyword before a function makes it return a Promise automatically.",
            "The await keyword pauses the execution until the Promise is resolved.",
            "You can only use await inside an async function.",
            "Error handling in async await is done using try-catch blocks.",
            "The fetch API is used to make HTTP requests and returns a Promise.",
            "Understanding async JavaScript is crucial for working with APIs and servers.",
        ]
    },
    {
        "number": "36",
        "title": "JavaScript Fetch API & Working with APIs",
        "segments": [
            "The Fetch API provides a modern way to make HTTP requests in JavaScript.",
            "Fetch returns a Promise that resolves to the Response object.",
            "The basic syntax is fetch URL then response then data catch error.",
            "The response.json method parses the response body as JSON.",
            "You can use fetch to get data from any public API on the internet.",
            "Let me show you an example using a free weather API.",
            "First, we call fetch with the API URL including our parameters.",
            "Then we chain .then to convert the response to JSON.",
            "Then we chain another .then to process the actual data.",
            "We can display this data on our webpage using DOM manipulation.",
            "For POST requests, you need to pass an options object as the second parameter.",
            "The options object includes method, headers, and body properties.",
            "The body should be converted to JSON string using JSON.stringify.",
            "Headers should include Content-Type application/json for JSON data.",
            "Using async await with fetch makes the code cleaner and easier to read.",
            "Error handling is important. Always handle network errors and non-OK responses.",
            "CORS, Cross-Origin Resource Sharing, is a security feature you might encounter.",
            "CORS blocks requests from different origins unless the server allows it.",
            "You can use a CORS proxy for development, but the server should handle CORS in production.",
            "APIs are how modern web applications communicate and share data.",
            "In your projects, you will frequently use fetch to get and send data to servers.",
            "Practice making API calls as it is an essential skill for web developers.",
        ]
    },
    {
        "number": "37",
        "title": "JavaScript Local Storage & Session Storage",
        "segments": [
            "Web Storage API allows you to store data in the browser.",
            "There are two types: localStorage and sessionStorage.",
            "localStorage data persists even after the browser is closed.",
            "sessionStorage data is cleared when the browser tab is closed.",
            "Both store data as key-value pairs where both key and value are strings.",
            "localStorage.setItem sets a key-value pair in local storage.",
            "localStorage.getItem retrieves the value for a given key.",
            "localStorage.removeItem removes a specific key-value pair.",
            "localStorage.clear removes all data from local storage.",
            "Since localStorage only stores strings, you need to use JSON methods for objects and arrays.",
            "Use JSON.stringify to convert an object to a string before storing.",
            "Use JSON.parse to convert the string back to an object when retrieving.",
            "The storage limit is usually around 5 to 10 megabytes depending on the browser.",
            "localStorage is great for saving user preferences, theme settings, and simple data.",
            "Never store sensitive data like passwords or tokens in localStorage.",
            "The storage event fires when localStorage is modified in another tab.",
            "This can be used to sync data across multiple tabs of the same website.",
            "Local storage is a simple but powerful tool for client-side data persistence.",
            "Many real-world applications use localStorage for caching and offline functionality.",
        ]
    },
    {
        "number": "38",
        "title": "JavaScript ES6+ Modern Features",
        "segments": [
            "ES6, also known as ECMAScript 2015, introduced many new features to JavaScript.",
            "We have already learned about let, const, arrow functions, and template literals.",
            "Destructuring assignment lets you extract values from arrays and objects into variables.",
            "Array destructuring uses square brackets. const [a, b] = [1, 2].",
            "Object destructuring uses curly braces. const {name, age} = person.",
            "The spread operator, three dots, expands an iterable into individual elements.",
            "The rest operator, also three dots, collects remaining elements into an array.",
            "Default parameters allow function parameters to have default values.",
            "The for-of loop iterates over iterable objects like arrays and strings.",
            "Maps are collections of key-value pairs where keys can be any data type.",
            "Sets are collections of unique values. Duplicate values are automatically removed.",
            "Symbols are unique and immutable data types used as object property keys.",
            "Optional chaining allows you to safely access deeply nested properties.",
            "Nullish coalescing operator returns the right operand when the left is null or undefined.",
            "Object shorthand properties allow you to omit the value if it matches the variable name.",
            "Computed property names let you use expressions as object property names.",
            "Modules allow you to split your code into separate files using import and export.",
            "Named exports can export multiple values. Default export exports a single value.",
            "The import statement is used to bring in values from other modules.",
            "Using modules makes your code more organized, maintainable, and reusable.",
            "Modern JavaScript is very powerful and expressive. These features will make you a better developer.",
        ]
    },
    {
        "number": "39",
        "title": "Exercise 4 - Weather App using Fetch API",
        "segments": [
            "In this exercise, you will build a weather application using HTML, CSS, and JavaScript.",
            "The app should have an input field where users can type a city name.",
            "When the user clicks search, the app should fetch weather data from an API.",
            "You can use the free OpenWeatherMap API for this exercise.",
            "Display the temperature, humidity, wind speed, and weather description.",
            "Add an appropriate weather icon based on the weather condition.",
            "The app should handle errors gracefully, like when a city is not found.",
            "Use async await with fetch for clean asynchronous code.",
            "Add some nice CSS to make the weather card look professional.",
            "Try to also show the city name and country in the display.",
            "This exercise combines DOM manipulation, events, fetch API, and async await.",
            "Take about an hour to attempt this exercise before watching the solution.",
            "Building API-based applications is a very important skill for web developers.",
        ]
    },
    {
        "number": "40",
        "title": "Exercise 4 Solution & Deployment Introduction",
        "segments": [
            "Let me now walk you through the complete solution for the weather app exercise.",
            "First, we create the HTML structure with an input, search button, and weather display div.",
            "We style it with CSS using a gradient background and glassmorphism effect for the card.",
            "In JavaScript, we create an async function called getWeather.",
            "We get the city name from the input and construct the API URL.",
            "We use try-catch with await fetch to make the API call.",
            "We check if the response is ok, otherwise throw an error.",
            "We parse the JSON response and extract temperature, humidity, and description.",
            "We update the DOM elements with the weather data using textContent.",
            "For the weather icon, we use the icon code from the API response.",
            "We also handle the error case by showing a friendly error message to the user.",
            "This is a complete real-world application that you can add to your portfolio.",
            "Before we end, let me briefly introduce you to deployment.",
            "Deployment means making your website available on the internet for everyone.",
            "GitHub Pages is a free way to deploy static websites directly from your GitHub repository.",
            "Netlify and Vercel are also excellent free platforms for deploying web applications.",
            "In the upcoming videos, we will learn about more advanced topics and frameworks.",
            "Congratulations on making it this far in the course. You have learned a lot.",
        ]
    },
]


def generate_json(video_data, base_duration=600):
    """Generate a realistic transcript JSON in the same format as Whisper output."""
    segments = video_data["segments"]
    num_segments = len(segments)
    avg_duration = base_duration / num_segments

    chunks = []
    current_time = 0.0

    for seg_text in segments:
        # Vary segment duration randomly (3-8 seconds per sentence)
        duration = avg_duration + random.uniform(-1.5, 1.5)
        duration = max(2.0, min(10.0, duration))

        chunks.append({
            "number": video_data["number"],
            "title": video_data["title"],
            "start": round(current_time, 2),
            "end": round(current_time + duration, 2),
            "text": f" {seg_text}"
        })
        current_time += duration

    full_text = " ".join(seg for seg in segments)
    return {"chunks": chunks, "text": full_text}


def main():
    jsons_dir = "jsons"

    total_chunks = 0
    for video in VIDEOS:
        # Longer videos for content-heavy topics
        duration = random.randint(500, 900)
        data = generate_json(video, base_duration=duration)
        total_chunks += len(data["chunks"])

        filename = f"{video['number'].zfill(2)}_{video['title']}.mp3.json"
        filepath = os.path.join(jsons_dir, filename)

        with open(filepath, "w") as f:
            json.dump(data, f)

        print(f"Generated: {filename} ({len(data['chunks'])} chunks)")

    print(f"\nTotal new videos: {len(VIDEOS)}")
    print(f"Total new chunks: {total_chunks}")
    print(f"\nNow run: python 5_migrate_to_chromadb.py")


if __name__ == "__main__":
    main()
